services:
  mysqldb:
    image: mysql
    container_name: mysql_cont
    environment:
      - MYSQL_ROOT_PASSWORD=change-me
      - MYSQL_DATABASE=redtires2
    ports:
      - '3307:3306'
    networks:
      - backend
  api:
    build: ./server
    depends_on:
      - mysqldb
    ports:
      - '4000:4000'
    command: npm run dev
    volumes:
      - mysqldb:/Users/rafaellopez/Desktop/Red-tires/db:var/lib/mysql
    networks:
      - backend
      - frontend

  client:
    build:
      context: ./client
     # dockerfile: ./src/Dockerfile

    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks:
      - frontend
    depends_on:
      - api

networks:
  backend:
  frontend:

volumes:
  mysqldb:
  client-data:
    name: client-data
